app/models.py
from werkzeug.security import generate_password_hash, check_password_hash
from flask_login import UserMixin,AnonymousUserMixin
###从flask_login导入UserMixin类
###USerMixin类包含的以上四种方法的默认实现。
from . import db, login_manager
###从程序的工厂函数引入login_manager实例
from itsdangerous import TimedJSONWebSignatureSerializer as Serializer
##导入生成令牌函数
from flask import current_app
from datetime import datetime


class Role_Url(db.Model):
    __tablename__ = 'roles_urls'
    id = db.Column(db.Integer, primary_key=True)
    rid = (db.String(64), db.ForeignKey('roles.id'))
    uid = (db.String(64), db.ForeignKey('urls.id'))

class Url(db.Model):
    __tablename__ = 'urls'
    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(64), unique=True)



class Role(db.Model):
    __tablename__ = 'roles'
    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(64), unique=True)

class User(UserMixin, db.Model):
    __tablename__ = 'users'
    id = db.Column(db.Integer, primary_key=True)

    email = db.Column(db.String(64), unique=True, index=True)

    name = db.Column(db.String(64))
    
    password_hash = db.Column(db.String(128))

    def ping(self):
        self.last_seen = datetime.utcnow()
        db.session.add(self)



    @property
    def password(self):
        raise AttributeError('password is not a readable attribute')

    @password.setter
    def password(self,password):
        self.password_hash = generate_password_hash(password)

    def verify_password(self, password):
        return check_password_hash(self.password_hash, password)

    def __repr__(self):
        return '<User %r>' % self.username

###很重要
@login_manager.user_loader
def load_user(user_uid):
    return User.query.get(int(user_uid))

app/__init__.py
from flask import Flask
from flask_bootstrap import Bootstrap
from flask_sqlalchemy import SQLAlchemy
from flask_login import LoginManager
from config import config

bootstrap = Bootstrap()
db = SQLAlchemy()
login_manager = LoginManager()
login_manager.session_protection = 'strong'
login_manager.login_view = 'auth.login'




def create_app(config_name):
    app = Flask(__name__)
    app.config.from_object(config[config_name])
    config[config_name].init_app(app)

    bootstrap.init_app(app)
    
    login_manager.init_app(app)

    db.init_app(app)

    from .main import main as main_blueprint
    app.register_blueprint(main_blueprint)

    #这个url_prefix加上后,在蓝本中定义的所有路由都会加上指定的前缀
    from .auth import auth as auth_blueprint
    app.register_blueprint(auth_blueprint, url_prefix='/auth')

    return app

app/main/__init__.py
from flask import Blueprint

main = Blueprint('main', __name__)

from .views import *

app/main/views.py
from . import main
from flask_login import login_required
from flask import render_template, request,flash


@main.route('/')
@login_required
def index():
	return render_template('index.html')


@main.route('/admin')
@login_required
def for_admins_only():
	return "管理员"


@main.route('/moderator')
@login_required
def for_moderators_only():
	return "评论修改者"


@main.route('/user')
@login_required
def userinfo():
	return render_template('user.html')

app/templates/base.html
{% extends "bootstrap/base.html" %}

{% block title %}Flasky{% endblock %}

{% block head %}
{{ super() }}
<link rel="shortcut icon" href="{{ url_for('static', filename='favicon.ico') }}" type="image/x-icon">
<link rel="icon" href="{{ url_for('static', filename='favicon.ico') }}" type="image/x-icon">
{% endblock %}

{% block navbar %}
<div class="navbar navbar-inverse" role="navigation">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="{{ url_for('main.index') }}">Toloog</a>
        </div>
        <div class="navbar-collapse collapse">
            <ul class="nav navbar-nav">
                <li><a href="{{ url_for('main.index') }}"></a></li>
            </ul>

            <!-- 判断条件中的变量current_user由Flask-Login定义，且在视图函数和模板中自动调用。 -->
            <ul class="nav navbar-nav navbar-right">
                
                {% if current_user %}
                <li><a href="{{ url_for('main.userinfo') }}">{{ current_user.name }}</a></li>
                <li><a href="{{ url_for('auth.logout') }}">退出</a></li>
                {% endif %}

            </ul> 
        </div>
    </div>
</div>
{% endblock %}

{% block content %}
<div class="container">
    {% for message in get_flashed_messages() %}
    <div class="alert alert-warning">
        <button type="button" class="close" data-dismiss="alert">&times;</button>
        {{ message }}
    </div>
    {% endfor %}

    {% block page_content %}{% endblock %}
</div>
{% endblock %}

{% block scripts %}
{{ super() }}

{% endblock %}

app/templates/index.html
{% extends "base.html" %}

{% block title %}测试{% endblock %}

{% block page_content %}
<div class="page-header">
    <h1>你好!</h1>
</div>

{% endblock %}

app/templates/user.html
{% extends "base.html"%}
{% block page_content %}

<div class="page-header">
	<h1>您好!{{ current_user.name }}</h1>


	
</div>
{% endblock %}